name: VM Deploy NodeBB

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ADMIN }}
          password: ${{ secrets.ADMIN_PASSWORD }}
          script: | 
            cd code/${{ secrets.REPO_NAME }}
            git pull origin main
            mkdir -p ./.docker/database/redis \
                     ./.docker/database/postgresql/data \
                     ./.docker/build \
                     ./.docker/public/uploads \
                     ./.docker/config

            chmod -R 0777 ./.docker
            docker compose down
            docker compose --profile redis up --build -d
#testing vm deploy

# testing VM Deploy
# Test that the docker down works
